Created first components
artabr/react-mentor-app pull request #1
Opened 2022-10-18 11:16 UTC by artabr

Created react components with all suggested methods.

2022-10-18 13:50 UTC, ViktorGuschin requested changes
Look good, but we need to remove unnecessary code.

2022-10-18 13:50 UTC, ViktorGuschin commented on src/components/Counter/Counter.tsx
> +        console.log("Counter rendered.");
I believe we didn't need log here.

2022-10-18 13:50 UTC, ViktorGuschin commented on src/components/Counter/CounterButton.tsx
> +        console.log("CounterButton rendered.");
Same with log

2022-10-19 09:51 UTC, artabr commented on src/components/Counter/CounterButton.tsx
> +        console.log("CounterButton rendered.");
I put it here to show that PureComponent works as intended and the buttons (CounterButton) don't rerender with the rerender of the parent component (Counter).
It's not a production-ready app so I believe there is no harm in logs here

2022-10-19 14:16 UTC, Tanya-atatakai commented on src/components/GenreTabs/GenreTab.tsx
> +               )}>{item?.title}</a>
in case you don't hame `item` at all, you will see the the whole component layout but only text will be empty. would you mind to add some checks here (like `if (!item) return null` before main return) and as well in `GenreTabs` component?
or maybe even think about not to make `item` and `items` optional at all since you always have them?

2022-10-31 18:39 UTC, merged